// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface BooleanArray
{
    // BooleanArray
    public int getLength();
    public void setLength(int length);
    public boolean getElement(int index);
    public void setElement(int index, boolean value);
}
