// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface ByteArray
{
    // ByteArray
    public int getLength();
    public void setLength(int length);
    public byte getElement(int index);
    public void setElement(int index, byte value);
}
