// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface DocumentFragment extends Node
{
    // DocumentFragment
    // NodeSelector
    public Element querySelector(String selectors);
    public NodeList querySelectorAll(String selectors);
}
