// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface DOMStringMap
{
    // DOMStringMap
    public String getElement(String name);
    public void setElement(String name, String value);
    public void createElement(String name, String value);
    public void deleteElement(String name);
}
