// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface DOMStringList
{
    // DOMStringList
    public int getLength();
    public String item(int index);
    public boolean contains(String string);
}
