// Generated by esidl 0.2.1.

package org.w3c.dom;

import org.w3c.dom.html.HTMLFormElement;

public interface FormData_Constructor
{
    // Constructor
    public FormData createInstance();
    public FormData createInstance(HTMLFormElement form);
}
