// Generated by esidl 0.2.1.

package org.w3c.dom;

import org.w3c.dom.file.Blob;

public interface FormData
{
    // FormData
    public void append(String name, Blob value);
    public void append(String name, String value);
}
