// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface UnsignedLongLongArray
{
    // UnsignedLongLongArray
    public int getLength();
    public void setLength(int length);
    public long getElement(int index);
    public void setElement(int index, long value);
}
