// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface UnsignedShortArray
{
    // UnsignedShortArray
    public int getLength();
    public void setLength(int length);
    public short getElement(int index);
    public void setElement(int index, short value);
}
