// Generated by esidl 0.2.1.

package org.w3c.dom;

public interface UnsignedLongArray
{
    // UnsignedLongArray
    public int getLength();
    public void setLength(int length);
    public int getElement(int index);
    public void setElement(int index, int value);
}
