/*
 * Copyright (c) 2009 John Pritchard, all rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package llg;

/**
 * This file is automatically generated by the build scripts.  
 * @since 1.1
 */
public final class Version {
    /**
     * Major version number.
     */
    public final static int Major = 0;
    /**
     * Minor version number.
     */
    public final static int Minor = 0;
    /**
     * HTTP Product Token in <code>" Major '.' Minor "</code>.
     */
    public final static java.lang.String Short = Major+"."+Minor;
    /**
     * Build sequence number.
     */
    public final static int Build = 3;
    /**
     * HTTP Product Token plus comment build date and time.  
     * As in <code>" Major '.' Minor '.' Build "</code>.
     */
    public final static java.lang.String Long = Short+'.'+Build;

    public final static java.lang.String Name = "llg";

    public final static java.lang.String Applet = Name+' '+Short+" from http://code.google.com/p/llg";

    public final static java.lang.String ToStringLong(String name){
        return (name+'/'+Long);
    }
    public final static java.lang.String ToStringShort(String name){
        return (name+'/'+Short);
    }
    public final static void PrintlnLong(String name){
        PrintlnLong(name,System.err);
    }
    public final static void PrintlnLong(java.io.PrintStream out){
        PrintlnLong("Syntelos",out);
    }
    public final static void PrintlnLong(String name, java.io.PrintStream out){
        out.println(ToStringLong(name));
    }
    public final static void PrintlnShort(String name){
        PrintlnShort(name,System.err);
    }
    public final static void PrintlnShort(java.io.PrintStream out){
        PrintlnShort("Syntelos",out);
    }
    public final static void PrintlnShort(String name, java.io.PrintStream out){
        out.println(ToStringShort(name));
    }

}
