package xs;

import com.google.appengine.api.xmpp.JID;

/**
 * This file is automatically generated by the build scripts.  
 * @since 1.1
 */
public final class Version {
    /**
     * Major version number.
     */
    public final static int Major = @VersionMajor@;
    /**
     * Minor version number.
     */
    public final static int Minor = @VersionMinor@;
    /**
     * HTTP Product Token in <code>" Major '.' Minor "</code>.
     */
    public final static java.lang.String Short = Major+"."+Minor;
    /**
     * Build sequence number.
     */
    public final static int Build = @VersionBuild@;
    /**
     * HTTP Product Token plus comment build date and time.  
     * As in <code>" Major '.' Minor '.' Build "</code>.
     */
    public final static java.lang.String Long = Short+'.'+Build;

    public final static java.lang.String Name = "@VersionName@";

    public final static JID From = new JID(Name+"@appspot.com");

    public final static java.lang.String Full = Name+'/'+Long;

    public final static java.lang.String Target = "@ProjectTarget@";

    public final static boolean IsTest = (Target.contains("-test"));

    public final static boolean IsProd = (!IsTest);
}
