package digi.as;

import gap.hapax.TemplateName;

/**
 * This file is automatically generated by the build scripts.  
 * @since 1.1
 */
public final class Version {
    /**
     * Major version number.
     */
    public final static int Major = @VersionMajor@;
    /**
     * Minor version number.
     */
    public final static int Minor = @VersionMinor@;
    /**
     * HTTP Product Token in <code>" Major '.' Minor "</code>.
     */
    public final static java.lang.String Short = Major+"."+Minor;
    /**
     * Build sequence number.
     */
    public final static int Build = @VersionBuild@;
    /**
     * HTTP Product Token plus comment build date and time.  
     * As in <code>" Major '.' Minor '.' Build "</code>.
     */
    public final static java.lang.String Long = Short+'.'+Build;

    public final static java.lang.String Name = "@VersionName@";

    public final static java.lang.String Target = "@ProjectTarget@";

    public final static boolean IsTest = (Target.contains("-test"));

    public final static boolean IsProd = (!IsTest);

    public final static java.lang.String ToStringLong(String name){
        return (name+'/'+Long);
    }
    public final static java.lang.String ToStringShort(String name){
        return (name+'/'+Short);
    }
    public final static void PrintlnLong(String name){
        PrintlnLong(name,System.err);
    }
    public final static void PrintlnLong(java.io.PrintStream out){
        PrintlnLong("Syntelos",out);
    }
    public final static void PrintlnLong(String name, java.io.PrintStream out){
        out.println(ToStringLong(name));
    }
    public final static void PrintlnShort(String name){
        PrintlnShort(name,System.err);
    }
    public final static void PrintlnShort(java.io.PrintStream out){
        PrintlnShort("Syntelos",out);
    }
    public final static void PrintlnShort(String name, java.io.PrintStream out){
        out.println(ToStringShort(name));
    }
    private final static lxl.Index<String> Index = new lxl.Index<String>();
    static {
        Index.put("long",0);
        Index.put("short",1);
        Index.put("number",2);
        Index.put("name",3);
        Index.put("target",4);
    }
    public final static boolean HasVariable(TemplateName name){
        if (name.is(0)){
            switch(Index.get(name.getTerm())){
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
                return true;
            default:
                return false;
            }
        }
        else
            return false;
    }
    public final static String GetVariable(TemplateName name){
        if (name.is(0)){
            switch(Index.get(name.getTerm())){
            case 0:
                return Version.Long;
            case 1:
                return Version.Short;
            case 2:
                return Version.Short;
            case 3:
                return Version.Name;
            case 4:
                return Version.Target;
            default:
                return null;
            }
        }
        else
            return null;
    }
}
