// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface CanvasPixelArray
{
    // CanvasPixelArray
    public int getLength();
    public byte getElement(int index);
    public void setElement(int index, byte value);
}
