// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface External
{
    // External
    public void AddSearchProvider(String engineURL);
    public int IsSearchProviderInstalled(String engineURL);
}
