// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLModElement extends HTMLElement
{
    // HTMLModElement
    public String getCite();
    public void setCite(String cite);
    public String getDateTime();
    public void setDateTime(String dateTime);
}
