// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLOptGroupElement extends HTMLElement
{
    // HTMLOptGroupElement
    public boolean getDisabled();
    public void setDisabled(boolean disabled);
    public String getLabel();
    public void setLabel(String label);
}
