// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLTableCaptionElement extends HTMLElement
{
    // HTMLTableCaptionElement
    // HTMLTableCaptionElement-7
    public String getAlign();
    public void setAlign(String align);
}
