// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLPreElement extends HTMLElement
{
    // HTMLPreElement
    // HTMLPreElement-27
    public int getWidth();
    public void setWidth(int width);
}
