// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLLegendElement extends HTMLElement
{
    // HTMLLegendElement
    public HTMLFormElement getForm();
    // HTMLLegendElement-18
    public String getAlign();
    public void setAlign(String align);
}
