// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLFormControlsCollection extends HTMLCollection
{
    // HTMLFormControlsCollection
    public Object namedItem(String name);
}
