// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLDListElement extends HTMLElement
{
    // HTMLDListElement
    // HTMLDListElement-10
    public boolean getCompact();
    public void setCompact(boolean compact);
}
