// Generated by esidl 0.2.1.

package org.w3c.dom.html;

import org.w3c.dom.DOMStringList;

public interface HTMLPropertiesCollection extends HTMLCollection
{
    // HTMLPropertiesCollection
    public PropertyNodeList namedItem(String name);
    public DOMStringList getNames();
}
