// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLQuoteElement extends HTMLElement
{
    // HTMLQuoteElement
    public String getCite();
    public void setCite(String cite);
}
