// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLDivElement extends HTMLElement
{
    // HTMLDivElement
    // HTMLDivElement-9
    public String getAlign();
    public void setAlign(String align);
}
