// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLParagraphElement extends HTMLElement
{
    // HTMLParagraphElement
    // HTMLParagraphElement-25
    public String getAlign();
    public void setAlign(String align);
}
