// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface HTMLTitleElement extends HTMLElement
{
    // HTMLTitleElement
    public String getText();
    public void setText(String text);
}
