// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface MessagePort
{
    // MessagePort
    public void postMessage(Object message);
    public void postMessage(Object message, Transferable[] transfer);
    public void start();
    public void close();
    public Function getOnmessage();
    public void setOnmessage(Function onmessage);
}
