// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface MutableTextTrack extends TextTrack
{
    // MutableTextTrack
    public void addCue(TextTrackCue cue);
    public void removeCue(TextTrackCue cue);
}
