// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface NavigatorUserMediaSuccessCallback
{
    // NavigatorUserMediaSuccessCallback
    public void handleEvent(LocalMediaStream stream);
}
