// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface NavigatorUserMediaErrorCallback
{
    // NavigatorUserMediaErrorCallback
    public void handleEvent(NavigatorUserMediaError error);
}
