// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface PeerConnection_Constructor
{
    // Constructor
    public PeerConnection createInstance(String configuration, SignalingCallback signalingCallback);
}
