// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface Screen
{
    // Screen
    public int getAvailWidth();
    public int getAvailHeight();
    public int getWidth();
    public int getHeight();
    public int getColorDepth();
    public int getPixelDepth();
}
