// Generated by esidl 0.2.1.

package org.w3c.dom.html;

import org.w3c.dom.events.Event;

public interface StreamEvent extends Event
{
    // StreamEvent
    public MediaStream getStream();
    public void initStreamEvent(String typeArg, boolean canBubbleArg, boolean cancelableArg, MediaStream streamArg);
}
