// Generated by esidl 0.2.1.

package org.w3c.dom.html;

public interface WindowModal
{
    // WindowModal
    public Object getDialogArguments();
    public String getReturnValue();
    public void setReturnValue(String returnValue);
}
