// Generated by esidl 0.2.1.

package org.w3c.dom.css;

public interface CSSComponentValue
{
    // CSSComponentValue
    public String getType();
    public Object getValue();
    public void setValue(Object value);
}
