// Generated by esidl 0.2.1.

package org.w3c.dom.css;

import org.w3c.dom.ObjectArray;

public interface CSSPropertyValueList
{
    // CSSPropertyValueList
    public ObjectArray<CSSValue> getList();
}
