// Generated by esidl 0.2.1.

package org.w3c.dom.css;

public interface CSSStringComponentValue
{
    // CSSStringComponentValue
    public String getString();
    public void setString(String string);
}
