// Generated by esidl 0.2.1.

package org.w3c.dom.css;

import org.w3c.dom.DOMException;

public interface DOMImplementationCSS
{
    // DOMImplementationCSS
    public CSSStyleSheet createCSSStyleSheet(String title, String media) throws DOMException;
}
