// Generated by esidl 0.2.1.

package org.w3c.dom.events;

public interface CustomEventInit extends EventInit
{
    // CustomEventInit
    public Object getDetail();
    public void setDetail(Object detail);
}
