// Generated by esidl 0.2.1.

package org.w3c.dom.events;

public interface EventInit
{
    // EventInit
    public boolean getBubbles();
    public void setBubbles(boolean bubbles);
    public boolean getCancelable();
    public void setCancelable(boolean cancelable);
}
