// Generated by esidl 0.2.1.

package org.w3c.dom.typedarray;

public interface DataView_Constructor
{
    // Constructor
    public DataView createInstance(ArrayBuffer buffer);
    public DataView createInstance(ArrayBuffer buffer, int byteOffset);
    public DataView createInstance(ArrayBuffer buffer, int byteOffset, int byteLength);
}
